name: Test Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, homologation, production]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Environment Variable
      run: echo "NODE_ENV=${{ matrix.environment }}" >> $GITHUB_ENV

    - name: Run Script
      run: node index.js
